spring:
  application:
    name: monolit

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}

  storage:
    avatar-path: ${AVATARS_PATH:./storage/avatars}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
