spring:
  application:
    name: monolit

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: кфвшщ

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: alexanderhanziuk@gmail.com
    password: qrcq ceug ruaj vjdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: jwt.secret=my-super-secret-key-that-is-at-least-32-bytes
  expiration: 86400000
