spring:
  application:
    name: monolit

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: кфвшщ

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: jwt.secret=my-super-secret-key-that-is-at-least-32-bytes
  expiration: 86400000
